Database Directory: 'D:\Docutap\Wrk\DB\'
Database Name: 'docutap'
Database Structure Name: 'docutap'
OpenEdge Install Directory: 'D:\Progress\OpenEdge\'
AWS Database Server: true
AWS Backup Site ID: ''
Backup Extract Location: 'G:\Replication\'
Backup Location: ''
BAK File Path: ''
Existing Database Backup Path: ''
Database Poll Attempts: '10'
Progress AppServers:
        - 'DashboardAS'
        - 'DtapAS'
        - 'DtapAS-RX'
        - 'DtapAS1'
        - 'SeamlessAS'
Services:
        - 'Docutap HL7 Service'
        - 'Docutap Messaging Server'
        - 'Docutap Relentless'
        - 'Docutap Seamless'

Progress Databases:
        - 'Docutap'
        - 'Docutap-RX'

Scrubber:
        File Path: 'D:\Deploy\Automated_Alpha\5.15_Scripts\StartScrubberCommandLine.r'
        Params: '-param "AWS|YES~DisplayMessages|NO~MachineType|1~ScrubType|3~ManuallyEditControls|NO~AppPath|D:\Docutap\Wrk~SysOdbc|docutap"'

Output Log File Path: 'D:\Deploy\Automated_Alpha\backupRestore.log'