Database Directory: 'D:\Progress\Wrk\db\'
Database Name: 'docutap'
Database Structure Name: 'docutap'
OpenEdge Install Directory: 'C:\Program Files\OpenEdge\'
AWS Database Server: false
Backup Extract Location: 'R:\Replication\'
Backup Location: '\\BACKUPSERVER\Progress A-D\DT001\AI\'
Database Poll Attempts: '10'
Progress AppServers:
        - 'DashboardAS'
        - 'DtapAS'
        - 'DtapAS-RX'
        - 'DtapAS1'
        - 'SeamlessAS'
Services:
        - 'Docutap eRx Server'
        - 'Docutap Attentive'
        - 'Docutap IM'
        - 'Docutap Relentless'
        - 'Docutap Seamless'
        - 'DtapHL7'
        - 'DtapFileTransporter'
Progress Databases:
        - 'DocuTAP'
        - 'DocuTAP-RX'

Scrubber:
        File Path: 'R:\Scrubbers\Scrubber.r'
        Params: '-param "AWS|NO~DisplayMessages|NO~MachineType|2~ScrubType|3~ManuallyEditControls|NO~AppPath|D:\Progress\Wrk~SysOdbc|docutap"'

Output Log File Path: 'D:\Deploy\Workspace\BackupRestoreOutputLogs\'
Error Log File Path: 'D:\Deploy\Workspace\BackupRestoreErrorLogs\'